
server:
  port: 8080

---

spring:
  devtools:
    livereload:
      enabled: true

---

spring:
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  mvc:
    static-path-pattern: /static/**

---

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: player
    password: player

---

mybatis:
  type-aliases-package: com.example.board
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true